### ISSUE TITLE
Subscriber Notifications

### ISSUE THREAD

**Issue by patrickulrich** [MattyIce/communitybot#1]
It would be nice to have subscription notification options. I could imagine a couple solutions off the top of my head. One of which would be to offer a reverse transaction for .001 with a memo for how long they subscribed and who subscribed them. The other could possibly be to comment on a post the bot upvotes saying how long they have remaining in their subscription or even offering a promo for the bot for new users to subscribe.

**Comment by MattyIce** [comment]
I've added the subscription notifications via transfer memos in this commit: https://github.com/MattyIce/communitybot/commit/ab06a599af1961e3290094dfb23af681d912be25

I will create a separate issue for the bot to post a comment on posts it upvotes.
