### ISSUE TITLE
Add SteemCleaner, Cheetah to classify bad content

### ISSUE THREAD

**Issue by KINGdotNET** [MattyIce/communitybot#4]
Hi Matt,
Please add steemcleaner, cheetah or other existing screener to help sanitize the content before community bot upvote. That would be a nice feature to have.

Cheers,
@yehey

**Comment by MattyIce** [comment]
Done in this commit: https://github.com/MattyIce/communitybot/commit/0b3dcb97bf27eeadc280b14b4d1f510566052252
