### ISSUE TITLE
Tag whitelist

### ISSUE THREAD

**Issue by patrickulrich** [MattyIce/communitybot#6]
I would like to see communitybot be able to set a configuration to only vote on content that is regarding the community tied tag. This would mean that as communitybot rolls through the members list for posts it would not vote for the most recent post if it was outside of the tag. Instead the ideal action would be to search the users posts in reverse order until it a) finds an unvoted post with the community tag then upvotes and moves to next user b) reaches the last post it upvoted / finds no tagged posts within voting range and then moves on to the next user in the members list.

**Comment by MattyIce** [comment]
Done in this commit: https://github.com/MattyIce/communitybot/commit/351f16aed40cd4daac0a2dcb195c1e6c692c39ec
